name: superbase_auth
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^14.8.1
  flutter_riverpod: ^2.6.1
  supabase_flutter: ^2.8.4
  sentry_flutter: ^8.14.1
  shared_preferences: ^2.5.3
  zoom_tap_animation: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
  fonts:
    - family: Manrope
      fonts:
        - asset: assets/fonts/Manrope.ttf
    - family: RadioCanadaBig
      fonts:
        - asset: assets/fonts/RadioCanadaBig.ttf
